# CONCANTENATİON

In [40]:
import numpy as np

In [41]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [42]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [43]:
z = np.array([1,5,0])

In [44]:
np.array([x,y,z])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 5, 0]])

* İki boyutlularda

In [48]:
a = ([[1,2,3],
      [5,6,7]])

In [52]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [5, 6, 7, 5, 6, 7]])