# INDEX İLE ELEMANLARA ERİŞMEK

In [63]:
import numpy as np

In [69]:
x = np.random.randint(10, size = 10)
x

array([7, 8, 1, 5, 0, 9, 3, 9, 7, 4], dtype=int32)

In [70]:
x[0]

np.int32(7)

In [72]:
x[0] = 100
x

array([100,   8,   1,   5,   0,   9,   3,   9,   7,   4], dtype=int32)

* İki boyutlu

In [75]:
y = np.random.randint(10,size = [3,5])
y

array([[1, 6, 8, 9, 2],
       [9, 6, 4, 5, 5],
       [6, 2, 4, 9, 3]], dtype=int32)

In [76]:
y[0,0]

np.int32(1)

In [80]:
y[2,4] = 2.2
y

array([[1, 6, 8, 9, 2],
       [9, 6, 4, 5, 5],
       [6, 2, 4, 9, 2]], dtype=int32)