# SPLİTTİNG

In [53]:
import numpy as np

In [54]:
x = np.array([1,2,3,3,5,5,6,7,8,8])

In [55]:
np.split(x,[4,7])

[array([1, 2, 3, 3]), array([5, 5, 6]), array([7, 8, 8])]

In [56]:
a,b,c = np.split(x, [4,7])

In [57]:
a

array([1, 2, 3, 3])

In [58]:
b

array([5, 5, 6])

In [59]:
c

array([7, 8, 8])