# FANCY

In [101]:
import numpy as np

x = np.arange(0,30,3)
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [102]:
x[1]

np.int64(3)

In [103]:
x[1], x[3], x[5]

(np.int64(3), np.int64(9), np.int64(15))

In [107]:
fancy = [1,3,5]
x

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [108]:
x[fancy]

array([ 3,  9, 15])

* İki boyutlu

In [109]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])