# MATEMATİKSEL İŞLEMLER

* ufunc

In [123]:
import numpy as np

In [124]:
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [126]:
np.subtract(x,1)

array([0, 1, 2, 3, 4])

In [127]:
np.add(x,2)

array([3, 4, 5, 6, 7])

In [128]:
np.multiply(x,22)

array([ 22,  44,  66,  88, 110])

In [129]:
np.divide(x,5)

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [130]:
np.power(x,3)

array([  1,   8,  27,  64, 125])

In [131]:
np.mod(x,2)

array([1, 0, 1, 0, 1])

In [132]:
np.absolute(np.array([-3]))

array([3])

In [133]:
np.sin(360)

np.float64(0.9589157234143065)

In [134]:
np.cos(90)

np.float64(-0.4480736161291701)

In [135]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [136]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])