# KOŞULLU ELEMAN İŞLEMLERİ

In [110]:
import numpy as np

x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [111]:
x > 5

array([False, False, False, False, False])

** With fancy

In [113]:
x[x > 3]

array([4, 5])

In [114]:
x[x >= 3]

array([3, 4, 5])

In [115]:
x[x <= 3]

array([1, 2, 3])

In [116]:
x[x == 3]

array([3])

In [117]:
x[x != 3]

array([1, 2, 4, 5])

----->

In [118]:
x

array([1, 2, 3, 4, 5])

In [119]:
x*2

array([ 2,  4,  6,  8, 10])

In [120]:
x/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [121]:
x*20/3

array([ 6.66666667, 13.33333333, 20.        , 26.66666667, 33.33333333])

In [122]:
x**3

array([  1,   8,  27,  64, 125])