# SLICING

In [81]:
import numpy as np

In [84]:
x = np.arange(20,30)
x

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [86]:
x[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [87]:
x[1:3]

array([21, 22])

In [88]:
x[0::2]

array([20, 22, 24, 26, 28])

* İki boyutlu

In [90]:
m = np.random.randint(10, size = (5,5))
m                      

array([[4, 8, 9, 7, 8],
       [2, 6, 1, 7, 1],
       [3, 4, 8, 2, 8],
       [6, 2, 7, 2, 7],
       [1, 2, 5, 3, 7]], dtype=int32)

In [91]:
m[:,0]

array([4, 2, 3, 6, 1], dtype=int32)

In [92]:
m[3:,0]

array([6, 1], dtype=int32)