# NUMPY ARRAY

In [5]:
import numpy as np

np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
a = np.array([1,2,3,4,5])

type(a)

numpy.ndarray

In [8]:
np.array([3.14,5,6,14])

array([ 3.14,  5.  ,  6.  , 14.  ])

Numpy kütüphanesi tek bir türde veri tutar o yüzden array içindekilerin hepsini float çevirdi

In [9]:
np.array([3.14,5,6,14], dtype="int")

array([ 3,  5,  6, 14])

"int" yazdım hepsini int formatında yazdı

## Sıfırdan Array Oluşturma

In [11]:
np.zeros(10, dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.full((2,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3]])

In [14]:
np.arange(3,31 ,4)

array([ 3,  7, 11, 15, 19, 23, 27])

3 ile 31 arasında 4'er artan doğrusal array

In [15]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

0 ile 1 arasında 10 farklı sayı oluşruran array

In [16]:
np.random.normal(10,4,(3,4))

array([[11.11810173,  8.87203261,  6.91237744,  2.32149615],
       [14.35986452, 10.63583488,  6.85581757,  9.8667925 ],
       [12.42766615,  9.52668284,  6.26828254, 16.53055289]])

Ortalama 10 satandart sapma 4 veren array

In [18]:
np.random.randint(0,10, (3,3))

array([[1, 9, 0],
       [1, 9, 3],
       [6, 6, 6]], dtype=int32)